### ISSUE TITLE
[이유정]Todo 

### ISSUE THREAD

**Issue by uuuuj** [Hojip-Kim/Worldisaster_Server#7]
Cloudfront 설정 로그
- [ ] 일단 Cloudfront 설정에서 사용자 정의 도메인 설정및 ssl설정 하지 않고, 넘어간 다음에 테스트해보았을때 문제가 생긴다면 그때 수정하기

- [x] Cloudfront, S3 설정 완료했고, CORS 설정도해줘야 하고, 다 하고 나면 S3 액세스 키를 우리 배포 서버의 환경변수에 저장해둬야 할 것 같음. 
- [ ] 환경변수에 저장해둔 다음에, video 업로드 (POST 요청) 코드 origin_dev에 올리고, EC2 서버 열어서 video 업로드 및 인코딩 잘 되는지 테스트. 그러려면 fmepg였나? 그거 서버에 설치해야됨. 그거 설정 해두기. 
- [x] S3 버킷에 인코딩 된 파일이 잘 업로드 되는지 확인한 뒤, Cloudfront에서 url 가져오는 코드 작성하고(Cloudfront url 부분만 수정해두면 됨)
- [ ] Nextjs로 마저 동영상 재생 코드 작성한 뒤, 성공하면 origin_dev와 합치기

뉴스 기사
- [ ] origin_dev에 있는 newDisasters와 합쳐서(내 RDS 사용해서 newDisasters및 다른 db table 모두 가져온 다음에 뉴스 기사 테스트하기
- [ ] 뉴스 기사 API 잘 동작하면 origin_dev에 내 코드 merge하기
